/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './theme/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#0f131f',
        surface: '#0f131f',
        surfaceVariant: '#313442',
        surfaceContainerLow: '#171b28',
        surfaceContainer: '#1b1f2c',
        surfaceContainerHigh: '#262a37',
        surfaceContainerHighest: '#313442',
        surfaceContainerLowest: '#0a0e1a',
        surfaceLight: '#353946',
        surfaceBorder: '#444650',
        outline: '#8e909c',
        outlineVariant: '#444650',
        primary: '#2ae500', 
        onPrimary: '#053900',
        primaryContainer: '#033000',
        onPrimaryContainer: '#1ca600',
        primaryDark: '#106e00',
        primaryLight: '#79ff5b',
        secondary: '#bdf4ff',
        onSecondary: '#00363d',
        secondaryContainer: '#00e3fd',
        onSecondaryContainer: '#00616d',
        tertiary: '#bdc2ff',
        onTertiary: '#1b247f',
        tertiaryContainer: '#111a77',
        onTertiaryContainer: '#7f88e5',
        success: '#2ae500',
        successDark: '#106e00',
        warning: '#f59e0b',
        warningDark: '#d97706',
        error: '#ffb4ab',
        onError: '#690005',
        errorContainer: '#93000a',
        onErrorContainer: '#ffdad6',
        danger: '#ffb4ab',
        dangerDark: '#93000a',
        gold: '#f59e0b',
        goldLight: '#fbbf24',
        textPrimary: '#dfe2f3',
        onSurface: '#dfe2f3',
        textSecondary: '#c5c6d2',
        onSurfaceVariant: '#c5c6d2',
        textMuted: '#8e909c',
        textInverse: '#0f131f',
        pitchGreen: '#0f131f',
        pitchLine: '#ffffff',
        pitchDark: '#0a0e1a',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '32px',
        '4xl': '40px',
        '5xl': '48px',
        '6xl': '64px',
      },
      borderRadius: {
        sm: '6px',
        md: '10px',
        lg: '14px',
        xl: '18px',
        '2xl': '24px',
        full: '9999px',
      },
      fontSize: {
        xs: '11px',
        sm: '13px',
        md: '15px',
        lg: '17px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '30px',
        '4xl': '36px',
        '5xl': '48px',
      },
      fontFamily: {
        regular: ['Inter_400Regular'],
        medium: ['Inter_500Medium'],
        semibold: ['Inter_600SemiBold'],
        bold: ['Inter_700Bold'],
        heading: ['PlusJakartaSans_600SemiBold'],
        headingBold: ['PlusJakartaSans_700Bold'],
        headingBlack: ['PlusJakartaSans_800ExtraBold'],
      },
    },
  },
  plugins: [],
};
